{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluffybot.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fluffybot.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fluffybot-pod-manager
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fluffybot.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fluffybot-pod-manager-binding
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fluffybot.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fluffybot.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: fluffybot-pod-manager
  apiGroup: rbac.authorization.k8s.io
{{- end }}
