apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fluffybot.labels" . | nindent 4 }}
    app: {{ .Values.webhook.name }}
spec:
  type: {{ .Values.webhook.service.type }}
  selector:
    {{- include "fluffybot.webhook.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.service.targetPort }}
      protocol: TCP
      name: http
